<?php
/**
 * Created by PhpStorm.
 * User: camph
 * Date: 29/08/2018
 * Time: 09:48
 */
$i = 0;
?>

<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>

        <tr class="<?= /* @escapeNotVerified */ $_code ?>">
            <?php if ($i == 0) {
                ?>
                <td rowspan="4" colspan="4" collapse="4"><textarea name="message" id="message" rows="6" cols="50" required></textarea></td>
                <?php
            }
            $i++;
            ?>

            <th <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()):?>
                    <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                <?php else:?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php endif?>
            </th>
            <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtml($_total->getLabel()) ?>">
                <?php if ($_total->getStrong()):?>
                    <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                <?php else:?>
                    <?= /* @escapeNotVerified */ $block->formatValue($_total) ?>
                <?php endif?>
            </td>
        </tr>
    <?php endif?>
<?php endforeach?>
