<?php
namespace Camph\Faq\Model\ResourceModel\Faq;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection
{
    
    public $_idFieldName = 'faq_id';

    public function __construct(
        \Magento\Framework\Data\Collection\EntityFactoryInterface $entityFactory,
        \Psr\Log\LoggerInterface $logger,
        \Magento\Framework\Data\Collection\Db\FetchStrategyInterface $fetchStrategy,
        \Magento\Framework\Event\ManagerInterface $eventManager,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\Framework\DB\Adapter\AdapterInterface $connection = null,
        \Magento\Framework\Model\ResourceModel\Db\AbstractDb $resource = null
    ) {
        $this->_init(
            'Camph\Faq\Model\Faq',
            'Camph\Faq\Model\ResourceModel\Faq'
        );
        parent::__construct(
            $entityFactory, $logger, $fetchStrategy, $eventManager, $connection,
            $resource
        );
        $this->storeManager = $storeManager;
    }

    /**
     * Define resource model
     *
     * @return void
     */

    public function addFieldToFilter($field, $condition = null)
    {
        if ($field === 'group') {
            $conditions = $condition;
            unset($condition);
            $i = 0;
            foreach ($conditions as $key => $values){
                if (is_array($values)){
                    foreach ($values as $value){
                        $condition[$i] = array('finset' => $value);
                        $i++;
                    }
                }
                else {
                    $condition = $conditions;
                }
            }

        }
        return parent::addFieldToFilter($field, $condition); // TODO: Change the autogenerated stub
    }
}
