<?php
/**
 * Created by PhpStorm.
 * User: camph
 * Date: 30/07/2018
 * Time: 16:24
 */
    /*echo $block->getAjaxData();*/
?>
<div>
    <div>
        <h2>Account Info</h2>
        <p>Username: </p>
        <p id="usr"></p>
        <p>Password: </p>
        <p id="pass"></p>
    </div>
    <div>
        <h2>Login Form</h2>
        <form method="post" id="form_login">
            <table>
                <tr>
                    <td>
                        <input type="text" name="username" id="username" placeholder="Tài khoản" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="text" name="password" id="password" placeholder="Mật khẩu" />
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <button id="button_login" type="button">Login</button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function(){
            $("#button_login").click(function(event){
                var data = $("form#form_login").serialize();
                alert(data);
                // sua lai url
                jQuery.ajax({
                    url: 'login',
                    type: "POST",
                    data: data,
                    showLoader: true,
                    success: function (data) {
                        console.log(data['username']);
                        console.log(data['password']);
                        $("#usr").text(data['username']);
                        $("#pass").text(data['password']);
                    },
                    error: function () {
                        alert("error");
                    }
                })
            });
        });
        $(document).ready(function(){
            $("#button_login").click(function(){
                var data = $("form#form_login").serialize();
                jQuery.ajax({
                    url: 'sendemail',
                    type: "POST",
                    data: data,
                    showLoader: true,
                    success: function () {
                        console.log("ok");
                    },
                    error: function () {
                        alert("error");
                    }
                })
            });
        });
    });


</script>

